Style/StringLiterals:
  EnforcedStyle: single_quotes
  AllowedPatterns:
    - /#{"[^"]*"}/

Style/BlockComments:
Naming/MethodParameterName:
Metrics/MethodLength:
Naming/PredicateName:
Metrics/CyclomaticComplexity:
Metrics/AbcSize:
Metrics/PerceivedComplexity:
  Enabled: false
